config/routes.rb
Rails.application.routes.draw do

  namespace :dynamic_select do
    get ':category_id/categories', to: 'categories#index', as: 'categories'
  end

  resources :families, only: [:show] do
    resources :members, only: [:new, :create, :destroy]
    resources :tasks do
      resources :comments, only: [:create]
    end
  end

  resources :comments, only: [:create] do
    resources :comments, only: [:create]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    invitations: 'users/invitations'
  }
  
  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end
end

app/models/task.rb
class Task < ApplicationRecord
  extend Enumerize

  resourcify
  acts_as_taggable

  belongs_to :author, class_name: :User
  belongs_to :assignee, class_name: :User, optional: true
  belongs_to :family

  has_many :comments, as: :commentable, dependent: :destroy
  has_and_belongs_to_many :categories, join_table: :categories_tasks

  enumerize :state, in: [:opened, :in_progress, :paused, :finished, :closed]

  validates :description,
            :author,
            presence: true

  delegate :first_name, to: :assignee, prefix: true, allow_nil: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource :family
  load_and_authorize_resource :task, through: :family, shallow: true

  def new
    @categories = []
  end

  def edit
    @task = Task.includes(:categories, comments: :comments).find(params[:id])
    @categories = @task.categories.sort_by(&:tree_level)
  end

  def index
    @author_tasks = current_user.author_tasks
  end

  def create
    @task.author = current_user
    @task.state = :opened

    if @task.save
      @task.category_ids = params[:task][:categories].values
      redirect_to family_tasks_path(@family)
    else
      render :new
    end
  end

  def update
    if @task.update_attributes(task_params)
      @task.category_ids = params[:task][:categories].values
      redirect_to family_tasks_path(@family)
    else
      render :edit
    end
  end


private

  def task_params
    params.require(:task).permit(:description, :tag_list)
  end

end

app/views/tasks/_form.html.haml
= simple_form_for [@family, @task] do |f|
  = f.input :description
  = f.input :tag_list, input_html: { value: f.object.tag_list.to_s }
  = f.simple_fields_for :categories do |c|
    = c.input :first_category_id, collection: Category.roots, label_method: :name, label: false, value_method: :id, include_blank: true, input_html: { id: :first_category_id, data: { url: dynamic_select_categories_path(':category_id'), target: '#second_category_id' } }, selected: @categories[0].try(:id), required: false
    = c.input :second_category_id, collection: @categories[0].try(:children) || [], label_method: :name, label: false, value_method: :id, include_blank: true, input_html: { id: :second_category_id, data: { url: dynamic_select_categories_path(':category_id'), target: '#third_category_id' } }, selected: @categories[1].try(:id), required: false, disabled: @categories[0].nil?
    = c.input :third_category_id, collection: @categories[1].try(:children) || [], label_method: :name, label: false, value_method: :id, include_blank: true, input_html: { id: :third_category_id }, selected: @categories[2].try(:id), required: false, disabled: @categories[1].nil?
  = f.button :submit

app/views/tasks/edit.html.haml
%h1= t('.title')

= render 'form'

%hr/
= render partial: @task.comments

%hr/
= render partial: 'comments/form', locals: { object: [@family, @task, Comment.new] }

app/views/tasks/index.html.haml
%h1
  #{@family.name}
  = t('.title')

%h2= t('.author_tasks')

.row
  - @author_tasks.each do |task|
    .task.col-md-2
      = task.description.truncate(20)
      = task.assignee_first_name
      %p
        %b= Task.human_attribute_name :state
        = task.state.text
      %p
        %b= Task.human_attribute_name :tag_list
        = task.tag_list
      %p
        = link_to edit_family_task_path(@family, task) do
          %i.glyphicon.glyphicon-edit

%hr/

.row
  - @family.users.each do |user|
    .user.col-md-2
      = user.first_name
      = user.email

%hr/
%p= link_to t('.new'), new_family_task_path(@family), class: 'btn btn-sm btn-primary'
%p= link_to t('.back_to_family'), family_path(@family), class: 'btn btn-sm btn-success'
%p= link_to t('.dashboard'), root_path, class: 'btn btn-sm btn-success'

app/views/tasks/new.html.haml
%h1= t('.title')

= render 'form'