config/routes.rb
Rails.application.routes.draw do

  namespace :dynamic_select do
    get ':category_id/categories', to: 'categories#index', as: 'categories'
  end

  resources :families, only: [:show] do
    resources :members, only: [:new, :create, :destroy]
    resources :tasks do
      resources :comments, only: [:create]
    end
  end

  resources :comments, only: [:create] do
    resources :comments, only: [:create]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    invitations: 'users/invitations'
  }
  
  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end
end

app/models/family.rb
class Family < ApplicationRecord
  resourcify

  has_many :users, through: :roles
  has_many :tasks

  validates :name, presence: true
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  load_and_authorize_resource

  def show
    @users = UserDecorator.decorate_collection(@family.users)
  end

end

app/views/families/show.html.haml
%h1
  = t('.title')
  %i= @family.name

%h2= t('.members')

%table.table.table-striped
  %thead
    %tr
      %th= User.human_attribute_name :first_name
      %th= User.human_attribute_name :last_name
      %th= User.human_attribute_name :nickname
      %th= User.human_attribute_name :birthday
      %th= User.human_attribute_name :email
      %th= User.human_attribute_name :role
      %th= User.human_attribute_name :rating
      %th
  %tbody
    - @users.each do |user|
      %tr
        %th= user.first_name
        %th= user.last_name
        %th= user.nickname
        %th= user.birthday_formatted
        %th= user.email
        %th= user.with_role(@family)
        %th= user.rating
        %th
          = link_to family_member_path(@family, user), method: :delete, data: { 'remove-id': user.id, confirm: t('messages.destruction_confirmation') }, class: 'btn btn-sm btn-danger' do
            %i.glyphicon.glyphicon-remove


%hr
%p= link_to t('.new_member'), new_family_member_path(@family), class: 'btn btn-sm btn-primary'
%p= link_to t('.new_task'), new_family_task_path(@family), class: 'btn btn-sm btn-primary'
%p= link_to t('.family_tasks'), family_tasks_path(@family), class: 'btn btn-sm btn-primary'
%p= link_to t('.dashboard'), root_path, class: 'btn btn-sm btn-success'