config/routes.rb
Rails.application.routes.draw do

  namespace :dynamic_select do
    get ':category_id/categories', to: 'categories#index', as: 'categories'
  end

  resources :families, only: [:show] do
    resources :members, only: [:new, :create, :destroy]
    resources :tasks do
      resources :comments, only: [:create]
    end
  end

  resources :comments, only: [:create] do
    resources :comments, only: [:create]
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'registrations',
    invitations: 'users/invitations'
  }
  
  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_family

  def new
    @user = User.new
  end

  def create
    FamilyMemberInvitationService.new(params[:user], @family).perform
    redirect_to @family
  end

  def destroy
    FamilyMemberRemoverService.new(params[:id], @family).perform
    redirect_to @family
  end

private

  def set_family
    @family = Family.find(params[:family_id])
  end

end

app/views/members/new.html.haml
%h1= t('.title')

= simple_form_for @user, url: family_members_path do |f|
  = f.input :id, collection: User.all - @family.users, label_method: :email, label: false, value_method: :id, prompt: :translate, required: false
  = f.input :email, required: true, label: false
  = f.input :role, as: :radio_buttons, collection: User::ROLES, required: true, checked: User::ROLES.first
  = f.button :submit